name: Generate attractions.js from API

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 1" # Cada lunes a las 3 AM UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install fetch dependency
        run: npm install node-fetch@2

      - name: Generate JS file
        run: |
          node ./scripts/generateAttractions.js

      - name: Debug Token Availability
        env:
          GH_TOKEN: ${{ secrets.MAPA_TURISMO_COLOMBIA }}
        run: |
          echo "Token is set: ${#GH_TOKEN}"

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MAPA_TURISMO_COLOMBIA }}@github.com/JuanPabloDiaz/turismo.git
          git remote -v
          git add assets/js/attractions.js
          git diff --staged --quiet || git commit -m "Update attractions.js from API"
          git push origin main
