name: Generate attractions.js from API

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 1-7 * 1" # Primer lunes del mes a las 3 AM UTC
    - cron: "0 3 15-21 * 1" # Tercer lunes del mes a las 3 AM UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Add this to give write permissions
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use built-in token

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install fetch dependency
        run: npm install node-fetch@2

      - name: Generate JS file
        run: |
          node ./scripts/generateAttractions.js

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/js/attractions.js
          git diff --staged --quiet || git commit -m "Update attractions.js from API"
          git push
